# Generated by Django 4.2.23 on 2025-08-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IoBaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email_address', models.EmailField(max_length=200, unique=True)),
                ('account_request', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sbiaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email_address', models.EmailField(max_length=200, unique=True)),
                ('account_request', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
