# Generated by Django 4.2.23 on 2025-08-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iobaccount',
            name='bank_name',
            field=models.CharField(default='SBI', max_length=200),
        ),
        migrations.AddField(
            model_name='sbiaccount',
            name='bank_name',
            field=models.CharField(default='SBI', max_length=200),
        ),
    ]
