# Generated by Django 4.2.23 on 2025-08-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_iobaccount_bank_name_sbiaccount_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iobaccount',
            name='bank_name',
            field=models.CharField(default='IOB', max_length=200),
        ),
    ]
