# Generated by Django 4.2.23 on 2025-08-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0003_alter_iobaccount_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='iobaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='sbiaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
