# Generated by Django 4.2.23 on 2025-08-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_iobaccount_account_number_sbiaccount_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='iobaccount',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='iobaccount',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='iobaccount',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='iobaccount',
            name='pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='iobaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sbiaccount',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='sbiaccount',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sbiaccount',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sbiaccount',
            name='pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sbiaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
