# Generated by Django 4.2.23 on 2025-08-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0005_iobaccount_aadhaar_iobaccount_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iobaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='sbiaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
