# Generated by Django 4.2.23 on 2025-08-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Bank', '0006_alter_iobaccount_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('trans_type', models.CharField(choices=[('CR', 'Credit'), ('DR', 'Debit')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('tran_date', models.DateTimeField(auto_now_add=True)),
                ('receiver_name', models.CharField(blank=True, max_length=200, null=True)),
                ('receiver_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
